### ISSUE TITLE
How can I setup this???

### ISSUE THREAD

**Issue by ghost** [ESX-PUBLIC/esx_joblogs#11]
I can't setup the jobs in the files which is called "CompatibleRessource". can you make a video record or add better instructions??

**Comment by rex2630** [comment]
This is not support or issue. So ask somewhere else please

**Comment by ghost** [comment]
I want support to setup it because he didn't add good instructions

**Comment by rex2630** [comment]
There are so easy installation steps. I dont know what are u talking about

**Comment by mariosmikroulis** [comment]
Hi. Let me explain. You haven't specified the steps correctly about how to set this up. We cloned the repository, we added the command to run on the server.cfg, and it seems like the jobs don't get logged because the joblogs don't trigger or listen anything with regards to the police or the other jobs you've added. Can we send you the teamviewer credentials and our discord to login and see with yourself what we mean?
